; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Jun 09 2019 12:12:10 GMT+0200 (Central European Summer Time)
M561                ; clear any bed transform
M98 Pdeployprobe.g  ; deploy mechanical Z probe
; Probe the bed at 4 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y350 H0 Z-99999
G30 P2 X300 Y350 H0 Z-99999
G30 P3 X300 Y15 H0 Z-99999 S
M98 Pretractprobe.g ; retract mechanical Z probe


