; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Jun 09 2019 12:12:11 GMT+0200 (Central European Summer Time)

