; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Jun 09 2019 12:12:11 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

